spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://kraju2k3_db_user:Raju_0219@cluster0.jjpluuz.mongodb.net/chatapp?retryWrites=true&w=majority

spring.data.mongodb.database=chatapp

server.port=8080